#!/usr/bin/env bash
# =============================================================================
# lib/viz-helper.sh
# =============================================================================
#
# Synopsis:
#     Shared Python source emitters for the visualization layer.
#
# Description:
#     Defines functions that emit Python source code as text. The emitted
#     source is concatenated into the Python heredocs used by
#     stages/static/89-viz.sh and lib/aggregate.sh (write_cluster_graph).
#     Factoring these primitives here avoids duplicating the treemap layout,
#     force-directed layout, color-scale, and SVG-chrome implementations
#     across two call sites.
#
#     Usage pattern:
#
#         source "$RETOOLKIT_LIB_DIR/viz-helper.sh"
#         "$VENV_PY" - <<PYEOF
#         $(viz_helper_emit_svg_chrome_py)
#         $(viz_helper_emit_color_scale_py)
#         $(viz_helper_emit_treemap_py)
#         ...
#         PYEOF
#
#     All emitted visualizations are self-contained: inline SVG with no
#     external CDN reference, no JavaScript library dependency, and no network
#     fetch at render time.
#
#     Sourced by analyze-binaries.sh; not directly executable.
#
# Provides:
#     viz_helper_emit_svg_chrome_py
#     viz_helper_emit_color_scale_py
#     viz_helper_emit_treemap_py
#     viz_helper_emit_force_layout_py
#
# Notes:
#     Visualization outputs are described in the wiki (Output-and-Reports).
#     Release history is recorded in CHANGELOG.md.
#
# Version:
#     3.7.3 - 2026-05-03
# =============================================================================

viz_helper_emit_svg_chrome_py() {
    cat <<'PYHELPER_CHROME'
# ---- viz_helper: SVG chrome and theme constants ----------------------------

VIZ_SEVERITY_COLORS = {
    "low":    "#4ade80",
    "medium": "#facc15",
    "high":   "#f87171",
    "info":   "#60a5fa",
    "dim":    "#6b7280",
}

VIZ_CSS_THEME = """
/* v3.0.7 (audit-11 E1) - aligned to RE-Toolkit-CHANGELOG / Usage-Guide /
 * per-binary report design system. Pre-v3.0.7 the viz HTML used a
 * different color scheme (--bg:#0a0e1a, --accent:#60a5fa) which
 * broke design continuity when operators clicked from the parent
 * report into a standalone viz page. v3.0.7 uses the same tokens as
 * stages/static/90-report.sh: --bg-primary:#1a1a1a, --accent:#5dade2,
 * Garamond, etc. */
:root {
    --bg-primary:   #1a1a1a;
    --bg-secondary: #242424;
    --bg-tertiary:  #2d2d2d;
    --bg-hover:     #363636;
    --text-primary:   #e8e8e8;
    --text-secondary: #b8b8b8;
    --text-muted:     #888;
    --accent:       #5dade2;
    --accent-dim:   #4a90c2;
    --border-color: #404040;
    --code-bg:      #2d2d2d;
    --severity-low:    #4ade80;
    --severity-medium: #facc15;
    --severity-high:   #f87171;
    --severity-crit:   #dc2626;
}
* { box-sizing: border-box; }
body {
    font-family: Garamond, "Times New Roman", serif;
    background: var(--bg-primary);
    color: var(--text-primary);
    margin: 0;
    padding: 24px;
    line-height: 1.5;
}
h1, h2, h3 { color: var(--text-primary); margin-top: 0; }
h1 { font-size: 22px; border-bottom: 1px solid var(--border-color); padding-bottom: 8px; margin-bottom: 16px; }
h2 { font-size: 19px; margin: 18px 0 10px; }
h3 { font-size: 17px; color: var(--text-primary); margin: 16px 0 8px; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
code {
    background: var(--code-bg);
    padding: 2px 6px;
    border-radius: 3px;
    font-family: Consolas, "Courier New", monospace;
    font-size: 13px;
    color: #d8d8d8;
}
.viz-container {
    background: var(--bg-secondary);
    border: 1px solid var(--border-color);
    border-radius: 6px;
    padding: 16px;
    margin: 16px 0;
}
.viz-meta {
    color: var(--text-secondary);
    font-size: 14px;
    margin-top: 8px;
}
.viz-footer {
    color: var(--text-muted);
    font-size: 12px;
    margin-top: 32px;
    border-top: 1px solid var(--border-color);
    padding-top: 12px;
    text-align: center;
}
svg { display: block; max-width: 100%; height: auto; }
svg text { font-family: Garamond, "Times New Roman", serif; }
.tooltip-trigger:hover { cursor: pointer; opacity: 0.8; }
"""

def svg_chrome_html(svg_body, title="RE-Toolkit visualization", subtitle=""):
    """Wrap SVG body in a complete standalone HTML document."""
    sub_html = f'<div class="viz-meta">{html_escape(subtitle)}</div>' if subtitle else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{html_escape(title)}</title>
<style>{VIZ_CSS_THEME}</style>
</head>
<body>
<h1>{html_escape(title)}</h1>
{sub_html}
<div class="viz-container">
{svg_body}
</div>
<div class="viz-footer">Generated by RE-Toolkit v2.9.0 - Inline SVG; no external dependencies.</div>
</body>
</html>
"""

def html_escape(s):
    """Minimal HTML/SVG attribute-safe escape."""
    if s is None: return ""
    s = str(s)
    return (s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;")
             .replace('"', "&quot;")
             .replace("'", "&#39;"))
PYHELPER_CHROME
}


# =============================================================================
# viz_helper_emit_color_scale_py
# =============================================================================
# Emits Python source defining color-interpolation helpers used across the
# visualization stages.
# =============================================================================
viz_helper_emit_color_scale_py() {
    cat <<'PYHELPER_COLOR'
# ---- viz_helper: color scales ----------------------------------------------

def color_entropy(entropy_value):
    """Map Shannon entropy (0.0 - 8.0) to a hex color.

    Low entropy (text/code) -> green; high entropy (compressed/encrypted)
    -> red. Uses linear interpolation through yellow at entropy=4.0.
    """
    try:
        e = float(entropy_value)
    except (ValueError, TypeError):
        return "#6b7280"
    if e <= 0.0: return "#4ade80"
    if e >= 7.5: return "#f87171"
    # Two-segment linear interpolation
    if e < 4.0:
        # green -> yellow as e goes 0 -> 4
        t = e / 4.0
        # green #4ade80 -> yellow #facc15
        r = int(0x4a + t * (0xfa - 0x4a))
        g = int(0xde + t * (0xcc - 0xde))
        b = int(0x80 + t * (0x15 - 0x80))
    else:
        # yellow -> red as e goes 4 -> 7.5
        t = (e - 4.0) / 3.5
        r = int(0xfa + t * (0xf8 - 0xfa))
        g = int(0xcc + t * (0x71 - 0xcc))
        b = int(0x15 + t * (0x71 - 0x15))
    return f"#{r:02x}{g:02x}{b:02x}"


def color_severity(name):
    """Map severity name (low/medium/high/info) to hex color."""
    return VIZ_SEVERITY_COLORS.get((name or "").lower(), "#6b7280")


def color_blend(color_a, color_b, t):
    """Linear interpolation between two #RRGGBB colors at t in [0, 1]."""
    def parse(c):
        c = c.lstrip("#")
        return int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16)
    ra, ga, ba = parse(color_a)
    rb, gb, bb = parse(color_b)
    r = int(ra + (rb - ra) * t)
    g = int(ga + (gb - ga) * t)
    b = int(ba + (bb - ba) * t)
    return f"#{r:02x}{g:02x}{b:02x}"
PYHELPER_COLOR
}


# =============================================================================
# viz_helper_emit_treemap_py
# =============================================================================
# Emits Python source defining squarify() - a treemap layout function.
# Implements the Bruls/Huijbregts/van Wijk squarified treemap algorithm
# in pure Python (no external deps).
# =============================================================================
viz_helper_emit_treemap_py() {
    cat <<'PYHELPER_TREEMAP'
# ---- viz_helper: squarified treemap layout ---------------------------------

def _normalize_sizes(sizes, total_area):
    total_size = sum(sizes) or 1
    return [s * total_area / total_size for s in sizes]


def _layout_row(row, x, y, w, h):
    """Place a row of rectangles within bounds; consumes the shorter dim."""
    total = sum(row)
    out = []
    if w >= h:
        # Lay out vertically along the left edge; consume width
        row_width = total / h if h > 0 else 0
        cy = y
        for sz in row:
            rh = sz / row_width if row_width > 0 else 0
            out.append((x, cy, row_width, rh))
            cy += rh
    else:
        # Lay out horizontally along the top edge; consume height
        row_height = total / w if w > 0 else 0
        cx = x
        for sz in row:
            rw = sz / row_height if row_height > 0 else 0
            out.append((cx, y, rw, row_height))
            cx += rw
    return out


def _worst(row, side):
    if not row or side <= 0: return float("inf")
    total = sum(row)
    if total <= 0: return float("inf")
    rmax = max(row); rmin = min(row)
    s2 = side * side
    t2 = total * total
    return max((s2 * rmax) / t2, t2 / (s2 * rmin))


def squarify(sizes, x, y, width, height):
    """Squarified treemap layout.

    Args:
        sizes: list of positive numbers; will be normalized to fit the
               given rectangle.
        x, y, width, height: target bounding rectangle.

    Returns:
        list of (x, y, w, h) tuples in the same order as input sizes.
    """
    if not sizes or width <= 0 or height <= 0:
        return [(x, y, 0, 0)] * len(sizes)
    sized = _normalize_sizes(sizes, width * height)
    # Greedy squarified layout
    placements = [None] * len(sized)
    indices = list(range(len(sized)))
    # Sort descending by size for stable layout (bigger rects first)
    indices.sort(key=lambda i: -sized[i])
    sorted_sizes = [sized[i] for i in indices]

    cx, cy, cw, ch = x, y, width, height
    pos = 0
    while pos < len(sorted_sizes):
        side = min(cw, ch)
        row = [sorted_sizes[pos]]
        next_pos = pos + 1
        while next_pos < len(sorted_sizes):
            new_row = row + [sorted_sizes[next_pos]]
            if _worst(new_row, side) <= _worst(row, side):
                row = new_row
                next_pos += 1
            else:
                break
        # Place the row
        rects = _layout_row(row, cx, cy, cw, ch)
        for i, rect in enumerate(rects):
            placements[indices[pos + i]] = rect
        # Shrink the available area
        if cw >= ch:
            consumed_w = rects[0][2] if rects else 0
            cx += consumed_w
            cw -= consumed_w
        else:
            consumed_h = rects[0][3] if rects else 0
            cy += consumed_h
            ch -= consumed_h
        pos = next_pos
    return placements
PYHELPER_TREEMAP
}


# =============================================================================
# viz_helper_emit_force_layout_py
# =============================================================================
# Emits Python source defining force_directed_layout() for graph
# visualization. Simplified Fruchterman-Reingold; converges in fixed
# number of iterations.
# =============================================================================
viz_helper_emit_force_layout_py() {
    cat <<'PYHELPER_FORCE'
# ---- viz_helper: force-directed graph layout -------------------------------

import math as _math
import random as _random


def force_directed_layout(nodes, edges, width, height, iterations=100, seed=42):
    """Compute 2D positions for graph nodes using a Fruchterman-Reingold-like
    spring model.

    Args:
        nodes: list of any hashable IDs.
        edges: list of (u, v) tuples; edge attractive force.
        width, height: bounding rectangle for layout.
        iterations: number of relaxation steps (more = smoother but slower).
        seed: RNG seed for reproducibility.

    Returns:
        dict mapping node ID -> (x, y) float coords.
    """
    if not nodes:
        return {}
    rnd = _random.Random(seed)
    n = len(nodes)
    # Initialize random positions inside the bounding box (with margin)
    margin = min(width, height) * 0.05
    positions = {
        node: (rnd.uniform(margin, width - margin),
               rnd.uniform(margin, height - margin))
        for node in nodes
    }
    if n < 2:
        return positions

    area = width * height
    # Optimal edge length
    k = _math.sqrt(area / n)
    # Initial temperature
    t = max(width, height) * 0.1

    # Build adjacency for fast edge lookup
    adj = {node: set() for node in nodes}
    for (u, v) in edges:
        if u in adj and v in adj:
            adj[u].add(v); adj[v].add(u)

    for it in range(iterations):
        # Repulsive forces (all pairs)
        disp = {node: [0.0, 0.0] for node in nodes}
        node_list = list(nodes)
        for i in range(len(node_list)):
            for j in range(i + 1, len(node_list)):
                u, v = node_list[i], node_list[j]
                dx = positions[u][0] - positions[v][0]
                dy = positions[u][1] - positions[v][1]
                dist = _math.sqrt(dx * dx + dy * dy) or 0.01
                force = (k * k) / dist
                fx = (dx / dist) * force
                fy = (dy / dist) * force
                disp[u][0] += fx; disp[u][1] += fy
                disp[v][0] -= fx; disp[v][1] -= fy

        # Attractive forces (edges only)
        for (u, v) in edges:
            if u not in positions or v not in positions:
                continue
            dx = positions[u][0] - positions[v][0]
            dy = positions[u][1] - positions[v][1]
            dist = _math.sqrt(dx * dx + dy * dy) or 0.01
            force = (dist * dist) / k
            fx = (dx / dist) * force
            fy = (dy / dist) * force
            disp[u][0] -= fx; disp[u][1] -= fy
            disp[v][0] += fx; disp[v][1] += fy

        # Apply displacement bounded by current temperature
        for node in nodes:
            dx, dy = disp[node]
            mag = _math.sqrt(dx * dx + dy * dy) or 0.01
            step = min(mag, t)
            x, y = positions[node]
            x += (dx / mag) * step
            y += (dy / mag) * step
            # Clamp to bounds with margin
            x = max(margin, min(width - margin, x))
            y = max(margin, min(height - margin, y))
            positions[node] = (x, y)

        # Cool down
        t = max(t * 0.95, 1.0)

    return positions
PYHELPER_FORCE
}
